peers = [
    { node_id = 1, listen = "127.0.0.1:45001" },
    { node_id = 2, listen = "127.0.0.1:45002" },
#    { node_id = 3, listen = "127.0.0.1:45003" },
]

db_path_pattern = ".run/node_{{node_id}}/db.sqlite3"

[partitions.User]
type = "regular"
filter.1 = "region == 'Hong Kong'"
filter.2 = "region == 'Beijing'"

[partitions.Article]
type = "regular"
filter.1 = "category == 'science'"
filter.2 = "category == 'technology'"

[partitions.Read]
type = "dependent"
dependentTable = "User"
dependentKey = "uid"

[partitions.PopularRank]
type = "regular"
filter.1 = "temporaGranularity == 'daily'"
filter.2 = "temporaGranularity == 'weekly' OR temporaGranularity == 'monthly'"

[partitions.BeRead]
type = "replicate"
