peers = [
    { node_id = 1, listen = "127.0.0.1:45001" },
    { node_id = 2, listen = "127.0.0.1:45002" },
]

db_path_pattern = ".run/node_{{node_id}}/db.sqlite3"

[partitions.User]
type = "regular"
filter.1 = "region == 'Hong Kong'"
filter.2 = "region == 'Beijing'"

[partitions.Article]
type = "regular"
filter.1 = "category == 'science'"
filter.2 = "category == 'technology'"

[partitions.Read]
type = "dependent"
dependency_table = "User"
dependency_key = "uid"

[partitions.PopularRank]
type = "replicate"

[partitions.BeRead]
type = "replicate"
