import sys
import os

# The code generated by protoc does not handle import path properly, so we need some DIRTY HACK
# Ref: https://github.com/protocolbuffers/protobuf/issues/1491
sys.path.append(os.path.abspath(os.path.dirname(__file__)) + "/generated")
from .generated import node_pb2 as node_pb, node_pb2_grpc as node_grpc
sys.path.pop()
